### ISSUE TITLE
Job queue is reprinting messages

### ISSUE THREAD

**Issue by egovedarov** [JC-IT/yii2-job-queue#2]
https://github.com/JC-IT/yii2-job-queue/blob/32ac92aef0b70c89cf26909d2209caa69312dd23/src/actions/DaemonAction.php#L76-L79

The `flush()` function has a parameter `$final` that is not used. It basically does the same as the foreach below it but includes removal of flushed messaged. So `flush(true)` can replace the whole foreach, because the job daemonAction is the final part of the execution for the job.

**Comment by joester89** [comment]
Fixed in v1.0.1 and v2.0.1

**Comment by egovedarov** [comment]
Thanks :)
